import os
import csv
from datetime import datetime
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from crewai_tools import SerperDevTool, TXTSearchTool

# Try importing gspread for direct Google Sheets updates
try:
    import gspread
    GSPREAD_AVAILABLE = True
except ImportError:
    GSPREAD_AVAILABLE = False

# ==========================================
# 1. Environment & Setup Configuration
# ==========================================
load_dotenv()

os.makedirs("knowledge", exist_ok=True)
os.makedirs("output", exist_ok=True)

docs_path = os.path.join("knowledge", "docs.txt")

# Target Google Sheet URL
SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/1HBD6iHd4X7S2BPbHs_FSZLw6d-C6YBXoLkJuTPfF1GY/edit?gid=0#gid=0"

# Replace line 28 in main.py:
web_search_tool = SerperDevTool(api_key=os.getenv("SERPER_API_KEY"))
# ==========================================
# 2. LLM & Tools Initialization
# ==========================================
llm = LLM(
    model="gpt-4o-mini",
    temperature=0.3
)

web_search_tool = SerperDevTool()
rag_tool = TXTSearchTool(txt=docs_path)

# ==========================================
# 3. Agent Definitions
# ==========================================

# AGENT 1: Internal Knowledge Base Specialist (RAG)
rag_support_agent = Agent(
    role="Internal Knowledge Base Specialist",
    goal="Answer customer inquiries accurately using internal documentation stored in the knowledge directory.",
    backstory=(
        "You are the frontline support specialist. You search local company files in the knowledge directory "
        "to answer incoming customer queries. If the internal knowledge base does not contain the answer, "
        "you MUST explicitly respond with the exact phrase: 'NEEDS_WEB_SEARCH'."
    ),
    tools=[rag_tool],
    llm=llm,
    verbose=True
)

# AGENT 2: Fallback Web Research Specialist
web_search_agent = Agent(
    role="Web Research Support Specialist",
    goal="Perform live internet searches using Serper search tool to answer customer questions.",
    backstory=(
        "You step in when internal documentation is insufficient. You are equipped with Serper web search. "
        "When Agent 1 flags 'NEEDS_WEB_SEARCH', you MUST execute your search tool to gather live information "
        "from the web and formulate a detailed, customer-ready answer."
    ),
    tools=[web_search_tool],
    llm=llm,
    verbose=True
)

# AGENT 3: Sheet Logging Agent
sheet_logger_agent = Agent(
    role="Support Interaction Data Logger",
    goal="Extract and format key details of the interaction into a structured single-line summary for Google Sheets entry.",
    backstory=(
        "You analyze customer inquiries and the final responses generated by previous agents, "
        "then output a clean single-sentence resolution summary ready to be stored in Google Sheets."
    ),
    llm=llm,
    verbose=True
)

# ==========================================
# Helper: Direct Google Sheets Logging Function
# ==========================================
def log_to_google_sheet(timestamp, inquiry, summary, source):
    if not GSPREAD_AVAILABLE:
        print("[!] gspread library not installed. Skipping direct Google Sheets update.")
        return False
    try:
        # Requires service_account.json in the project root folder
        gc = gspread.service_account(filename="service_account.json")
        sh = gc.open_by_url(SPREADSHEET_URL)
        worksheet = sh.sheet1

        # Initialize header row if spreadsheet is empty
        if len(worksheet.get_all_values()) == 0:
            worksheet.append_row(["Timestamp", "Customer Inquiry", "Answer / Resolution", "Source / Agent Used"])

        worksheet.append_row([timestamp, inquiry, summary, source])
        print(f"[✓] Successfully appended entry directly to Google Sheet!")
        return True
    except Exception as e:
        print(f"[!] Could not write to Google Sheets directly ({e}). Saved to CSV locally.")
        return False

# ==========================================
# 4. Pipeline Execution Function
# ==========================================
def run_support_pipeline():
    print("\n" + "="*60)
    print("   CREWAI MULTI-AGENT SUPPORT SYSTEM (RAG -> WEB -> LOG)")
    print("="*60)
    
    user_inquiry = input("\nEnter customer inquiry:\n> ").strip()
    if not user_inquiry:
        print("[-] No inquiry entered. Exiting.")
        return

    # TASK 1: Internal RAG Search (Agent 1)
    rag_task = Task(
        description=(
            f"Search local knowledge base files for an answer to this inquiry:\n'{user_inquiry}'\n"
            "If the answer is found in local docs, compose a clear response. "
            "If missing, output ONLY: 'NEEDS_WEB_SEARCH'."
        ),
        expected_output="A customer support response grounded in local docs OR 'NEEDS_WEB_SEARCH'.",
        agent=rag_support_agent
    )

    # TASK 2: Web Search Fallback (Agent 2)
    web_search_task = Task(
        description=(
            f"Review output from Task 1. If Task 1 outputted 'NEEDS_WEB_SEARCH', "
            f"use your web search tool to search for: '{user_inquiry}'. "
            "Provide a complete, informative response based on search results."
        ),
        expected_output="A complete customer support response based on live web search results.",
        agent=web_search_agent,
        context=[rag_task]
    )

    # TASK 3: Spreadsheet Data Formatting (Agent 3)
    logging_task = Task(
        description=(
            f"Review customer inquiry ('{user_inquiry}') and the response from Task 2. "
            "Create a clean single-sentence summary of the resolution for spreadsheet logging."
        ),
        expected_output="A clean single-sentence summary of the final resolution.",
        agent=sheet_logger_agent,
        context=[rag_task, web_search_task]
    )

    # Assemble Sequential Crew
    customer_support_crew = Crew(
        agents=[rag_support_agent, web_search_agent, sheet_logger_agent],
        tasks=[rag_task, web_search_task, logging_task],
        process=Process.sequential,
        verbose=True
    )

    print("\n[+] Executing CrewAI Sequential Workflow...\n")
    result = customer_support_crew.kickoff()

    print("\n================ FINAL RESPONSE ================\n")
    print(result.raw)

    # Data formatting for logging
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    clean_summary = str(result.raw).replace("\n", " ").strip()
    source = "Web Search" if "NEEDS_WEB_SEARCH" in str(rag_task.output) else "Internal Docs"

    # 1. Local CSV Backup Logging
    csv_file_path = os.path.join("output", "support_sheet_logs.csv")
    file_exists = os.path.isfile(csv_file_path)

    with open(csv_file_path, "a", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(["Timestamp", "Customer Inquiry", "Answer / Resolution", "Source / Agent Used"])
        writer.writerow([timestamp, user_inquiry, clean_summary, source])

    print(f"[✓] Logged locally to: {csv_file_path}")

    # 2. Live Google Sheets Upload
    log_to_google_sheet(timestamp, user_inquiry, clean_summary, source)

# ==========================================
# 5. Program Entry Point
# ==========================================
if __name__ == "__main__":
    run_support_pipeline()